[package]
name = "proarc_file_transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
proarc_utils = { path = "../proarc_utils" }

tokio = { version = "1.0", features = ["full"] }
dotenvy = "0.15.7"