[package]
name = "proarc_database"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.3", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.0", features = ["full"] }
dotenvy = "0.15.7"
sha256 = "1.6.0"
rand = "0.8.5"